---
title: "01_data_process_ple_react"
author: "Levente Ronai"
output: html_document
---

```{r, message = F, warning = F}

options(scipen = 999)

### loading packages

library(psych)
library(tidyverse)
library(dplyr)
library(data.table)
library(git2r)
library(lavaan)
library(semTools)

```

importing datasets

```{r}

big_data <- read.csv("data_processed/big_data.csv")

dat_cleaned <- 
  big_data %>% 
  select(id_esm, age, gender, edu, city, start_date, date_esm, date_diary,
         day, beep, event_pleasantness,
         contains(c("mss_", "ple_", "stressor")), -contains(c("minutes")))

write.csv(dat_cleaned, "data_processed/dat_cleaned.csv", row.names = F)

```

```{r}

dat_cleaned  <-  
  dat_cleaned %>%
  mutate(gender = factor(gender, levels = c(1, 2, 3), labels = c("Female", "Male", "Other")),
         event_unpleasantness = 8-event_pleasantness)

```

multilevel confirmatory factor analysis for psychotic-like experiences (within/between levels)

```{r, warning = T}

cfa_ple <-
  dat_cleaned %>%
  filter(!is.na(date_esm)) %>%
  select(id_esm, date_esm, beep,
         ple_control, ple_strange, ple_thoughts, ple_suspicion,
         ple_treatment, ple_perception, ple_thougtscontrol, ple_familiarstrange) %>%
  filter_at(vars(ple_control:ple_familiarstrange), all_vars(!is.na(.))) %>%
  distinct() %>%
  ungroup()

cfa_ple_syntax <- '

  level: 1

      ple_within   =~    ple_control + ple_strange + ple_thoughts + ple_suspicion +
                         ple_treatment + ple_perception + ple_thougtscontrol + ple_familiarstrange
                         
                         ple_perception	~~	ple_familiarstrange
                         ple_thoughts	~~	ple_familiarstrange


  level: 2

      ple_between   =~   ple_control + ple_strange + ple_thoughts + ple_suspicion +
                         ple_treatment + ple_perception + ple_thougtscontrol + ple_familiarstrange
                         
                        ple_control	~~	ple_strange

'

fit_ple <- cfa(model = cfa_ple_syntax, data = cfa_ple, cluster = "id_esm", std.lv = TRUE, estimator = "MLR")

```


```{r, warning = T}
fitMeasures(fit_ple, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr_within", "srmr_between"))
```


```{r, warning = T}

summary(fit_ple, fit.measures = TRUE, standardize = TRUE)


modificationindices(fit_ple) %>%
  select("lhs", "op", "rhs", "level", "mi") %>%
  filter(mi > 11) %>%
  arrange(desc(mi)) %>%
  head(n = 10) %>%
  print()

```

```{r, warning = T}

# within-person factor loadings
(inspect(fit_ple, what = "std")$within$lambda)

# between-person factor loadings
(inspect(fit_ple, what = "std")$id_esm$lambda)

# reliability of NA model
(reliability(fit_ple))

```


```{r, warning = T}

dat_ple_lev_2 <-
  cfa_ple %>%
  select(id_esm) %>%
  distinct() %>%
  cbind(lavPredict(fit_ple, newdata = cfa_ple[4:11], level = 2L))

dat_ple_lev_1 <-
  cfa_ple %>%
  cbind(lavPredict(fit_ple, newdata = cfa_ple[4:11], level = 1L)) %>%
  select(-c(ple_control:ple_familiarstrange))

dat_ple <-
  dat_ple_lev_1 %>%
  left_join(dat_ple_lev_2, by = "id_esm") %>%
  mutate(ple_cfa =  ple_within + ple_between)

dat_cleaned <-
  dat_cleaned %>% 
  left_join(dat_ple, by = c("id_esm", "date_esm", "beep"))


```

cronbach's alpha for mss (exclude #10 and #5 due to negative variances)

```{r}
# positive schizotypy: 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38
mss_pos <- 
  dat_cleaned %>%
  select(id_esm, MSS_BH_8, MSS_BH_11, MSS_BH_14, 
           MSS_BH_23, MSS_BH_32, MSS_BH_20, MSS_BH_26, MSS_BH_29, MSS_BH_2, MSS_BH_38, MSS_BH_17, MSS_BH_35) %>% 
  # MSS_BH_5
  distinct() %>% 
  select(-id_esm)

# negative schizotypy: 1, 4R, 7, 10R, 13, 16, 19, 22, 25R, 28, 31, 34, 37R
mss_neg <- 
  dat_cleaned %>%
  select(id_esm, MSS_BH_1, MSS_BH_28, MSS_BH_13, MSS_BH_34, MSS_BH_19, MSS_BH_4, MSS_BH_7, MSS_BH_16,
             MSS_BH_25, MSS_BH_31, MSS_BH_37, MSS_BH_22) %>% 
  # MSS_BH_10
  distinct() %>% 
  select(-id_esm)

# disorganized schizotypy: 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36  
mss_dis <- 
  dat_cleaned %>%
  select(id_esm, MSS_BH_3, MSS_BH_6, MSS_BH_9, 
           MSS_BH_12, MSS_BH_15, MSS_BH_18, 
           MSS_BH_21, MSS_BH_24, MSS_BH_27, 
           MSS_BH_30, MSS_BH_36, MSS_BH_33) %>%
  distinct() %>% 
  select(-id_esm)
```


```{r}
psych::alpha(mss_pos, check.keys=TRUE)
```

```{r}
psych::alpha(mss_neg, check.keys=TRUE)
```


```{r}
psych::alpha(mss_dis, check.keys=TRUE)
```

# CFA for MSS

```{r}

# positive schizotypy: 2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38
# affective schizotypy: 1, 28, 13, 19, 34, 
# social schizotypy: 4R, 7, 10R, 16, 22, 25R, 31, 37R

# negative schizotypy: 1, 4R, 7, 10R, 13, 16, 19, 22, 25R, 28, 31, 34, 37R


# disorganized schizotypy: 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36

dat_cfa_mss <- 
  dat_cleaned %>% 
  dplyr::select(id_esm, contains("MSS_BH")) %>%
  distinct()
  
cfa_mss <- '


mss_pos_score =~  MSS_BH_8 +  MSS_BH_11 +  MSS_BH_14  +
                  MSS_BH_20 + MSS_BH_26 +  MSS_BH_29 +
                  MSS_BH_23 + MSS_BH_32 + MSS_BH_17 + MSS_BH_35 + MSS_BH_38 + MSS_BH_2 # +MSS_BH_5
            
mss_neg_score =~  MSS_BH_19 + MSS_BH_28 + MSS_BH_13 + 
                  MSS_BH_34 + MSS_BH_1 + MSS_BH_4 + MSS_BH_7 + # MSS_BH_10 + 
                  MSS_BH_16 + MSS_BH_25 + MSS_BH_31 + MSS_BH_37 + MSS_BH_22

mss_dis_score =~  MSS_BH_3 + MSS_BH_6 + MSS_BH_9 +
                  MSS_BH_12 + MSS_BH_15 + MSS_BH_18 +
                  MSS_BH_21 + MSS_BH_24 + MSS_BH_27 +
                  MSS_BH_30 + MSS_BH_36 + MSS_BH_33 
                  
'

fit_mss <- cfa(model = cfa_mss, # ordered = T,
                                ordered = c('MSS_BH_1', 'MSS_BH_2',
                                            'MSS_BH_3', 'MSS_BH_4',
                                            'MSS_BH_5', 'MSS_BH_6',
                                            'MSS_BH_7', 'MSS_BH_8',
                                            'MSS_BH_9', 'MSS_BH_10',
                                            'MSS_BH_11', 'MSS_BH_12',
                                            'MSS_BH_13', 'MSS_BH_14',
                                            'MSS_BH_15', 'MSS_BH_16',
                                            'MSS_BH_17', 'MSS_BH_18',
                                            'MSS_BH_19', 'MSS_BH_20',
                                            'MSS_BH_21', 'MSS_BH_22',
                                            'MSS_BH_23', 'MSS_BH_24',
                                            'MSS_BH_25', 'MSS_BH_26',
                                            'MSS_BH_27', 'MSS_BH_28',
                                            'MSS_BH_29', 'MSS_BH_30',
                                            'MSS_BH_31', 'MSS_BH_32',
                                            'MSS_BH_33', 'MSS_BH_34',
                                            'MSS_BH_35', 'MSS_BH_36',
                                            'MSS_BH_37', 'MSS_BH_38'),
                data = dat_cfa_mss, std.lv = TRUE, estimator = "WLSMV")

```

```{r}
fitMeasures(fit_mss, c("chisq", "df", "pvalue", "cfi", "tli",
                   "rmsea", "srmr"))
```

```{r}
modificationindices(fit_mss) %>%
  select("lhs", "op", "rhs", "mi") %>%
  arrange(desc(mi)) %>%
 # head(n = 10) %>%
  print()
```

```{r}

summary(fit_mss, fit.measures = TRUE, standardize = TRUE)

```


```{r}
# reliability of factors (omega)
(reliability(fit_mss))

# factor loadings
inspect(fit_mss, what = "std")$lambda

```

```{r, warning = T}

dat_cfa_mss_scores <-
  dat_cfa_mss %>%
  select(id_esm) %>%
  distinct() %>%
  cbind(lavPredict(fit_mss, newdata = dat_cfa_mss[2:39]))

dat_cleaned <-
  dat_cleaned %>% 
  left_join(dat_cfa_mss_scores, by = c("id_esm"))


```

```{r}

# dat_cleaned <-
#   dat_cleaned %>%
#   arrange(id_esm, day, beep) %>%
#   group_by(id_esm, day) %>%
#   mutate_at(vars(negaff_cfa,
#                  ambivalence_centered, 
#                  negaff_cfa_centered,
#                  posaff_cfa_centered,
#                  ple_cfa_centered,
#                  event_unpleasantness,
#                  event_pleasantness_centered,
#                  event_unpleasantness_centered,
#                  gonogo_dprime_centered,
#                  nback_dprime_centered,
#                  gonogo_corr_rt_median_centered,
#                  nback_corr_rt_median_centered),
#             .funs = list(lag = ~ lag(.))) %>%
#   ungroup() %>% 
#   distinct()

# dat_cleaned <-
#   dat_cleaned %>%
#   group_by(id_esm) %>%
#   mutate_at(vars(ambivalence,
#                  negaff_cfa,
#                  posaff_cfa,
#                  ple_cfa,
#                  event_pleasantness,
#                  event_unpleasantness,
#                  gonogo_dprime,
#                  nback_dprime,
#                  gonogo_corr_rt_median,
#                  nback_corr_rt_median),
#             .funs = list(mean = ~ mean(., na.rm = T))) %>%
#   ungroup()

```

centering variables, calculating 3days mean of momentary perceived distress, recoding objectified distressors

```{r}


dat_cleaned <-
  dat_cleaned %>%
  mutate(
    diary_counter =
      case_when(
        day <= 3  ~ 1,
        day <= 6  ~ 2,
        day <= 9  ~ 3,
        day <= 12 ~ 4,
        day <= 15 ~ 5,
        day <= 18 ~ 6,
        day <= 21 ~ 7,
        day <= 24 ~ 8,
        day <= 27 ~ 9,
        day <= 30 ~ 10,
      )
    )
# 
# dat_cleaned <- 
#   dat_cleaned %>%
#   group_by(id_esm, diary_counter) %>%
#   fill(c(dep_sum, dep_within, diary_counter, date_diary), .direction = "updown") %>% 
#   ungroup() %>% 
#   group_by(id_esm) %>%
#   fill(dep_between, .direction = "updown") %>% 
#   ungroup()
 
dat_cleaned <- 
  dat_cleaned %>% 
  group_by(id_esm) %>%
  mutate_at(vars(stressor_sum, ple_cfa, event_unpleasantness),
            .funs = list(centered = ~ scale(., scale = F, center = T))) %>% 
  distinct() %>% 
  ungroup() %>%
  group_by(id_esm, diary_counter) %>% ###NE DATE DIARY SZERINT HANEM COUNTER!!!!
  mutate(event_unpleasantness_3days_mean = mean(event_unpleasantness, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(stressor_sum_centered_int = stressor_sum_centered * -1)
```


# 5: creation of final dataset for modeling

```{r}

# data for beep models - select model-relevant variables  

model_dat <-
  dat_cleaned %>%
  select(id_esm, edu, gender, age, city, start_date, date_diary, day, beep, diary_counter,

         event_unpleasantness, event_unpleasantness_centered, 
         
         ple_cfa, ple_cfa_centered, ple_between, 
         ple_control, ple_strange, ple_thoughts,
         ple_suspicion, ple_treatment, ple_thougtscontrol, ple_sum,

         contains(c("_mean", "stressor_sum")),
         mss_dis, mss_pos, mss_neg, 
         mss_dis_score, mss_pos_score, 
         mss_neg_score, 
         ) %>%
  distinct()

```

```{r}

write.csv(model_dat, "data_processed/model_dat.csv", row.names = F)

```

