---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r}
library(tidyverse)
library(lavaan)
library(semTools)
```

## import data

```{r}
big_data <- read.csv("data_processed/big_data.csv")

dat <- 
  big_data %>% 
  select(id_esm, session_esm, created_esm, age, gender, edu, city, start_date, date_esm, date_diary, three_day_block,
         day, beep, event_pleasantness, sad, afraid, unrested, angry, irritated, worried,
         contains(c("mss_", "ple_", "stressor", "SCL_90_depr_diary_")), -contains(c("minutes")))
```


```{r}
## prep data


dat_diary <-
  dat %>% 
  group_by(id_esm, three_day_block) %>% 
  mutate(
    across(
      c(angry, sad, irritated, worried, afraid,
        ple_strange, ple_thoughts, ple_suspicion, ple_treatment, event_pleasantness,
        ple_perception, ple_thougtscontrol, ple_familiarstrange),
      ~mean(., na.rm = T),
      .names = "{.col}_diarymean"
    )
  ) %>% 
  ungroup() %>% 
  distinct(id_esm, three_day_block, .keep_all = T)

```

# exploration

```{r}
dat_diary %>% 
  select(stressor_1:stressor_19, stressor_21, SCL_90_depr_diary_1:SCL_90_depr_diary_13) %>% 
  pivot_longer(stressor_1:SCL_90_depr_diary_13, names_to = "stressor_no", values_to = "score") %>% 
  ggplot(aes(score)) + 
  geom_histogram() + 
  facet_wrap(~stressor_no)

```


```{r}
dat_diary %>% 
    pivot_longer(stressor_1:stressor_18, names_to = "stressor_no", values_to = "score") %>% 
  count(stressor_no, score)
```


# hypothesis testing

## formative models

### stressor to negaff and ple reflective latents

```{r}
sem_stressor_formative <- 
  "
level: 1
  
  stressor_total_w <~ 1*stressor_9+stressor_10+stressor_11+stressor_12+stressor_13+stressor_15+stressor_16+stressor_17
  ple_latent_w =~ ple_strange_diarymean + ple_thoughts_diarymean + ple_suspicion_diarymean + ple_treatment_diarymean + ple_perception_diarymean + ple_thougtscontrol_diarymean + ple_familiarstrange_diarymean
  negaff_latent_w =~ angry_diarymean + sad_diarymean + irritated_diarymean + worried_diarymean
  
  ple_latent_w ~ stressor_total_w 
  negaff_latent_w ~ stressor_total_w 
  
  # based on mi's
  ple_suspicion_diarymean	~~	ple_treatment_diarymean
  sad_diarymean	~~	worried_diarymean
  ple_thoughts_diarymean	~~	ple_suspicion_diarymean
  ple_perception_diarymean	~~	ple_familiarstrange_diarymean
  
level: 2
  
  ple_latent_b =~ ple_strange_diarymean + ple_thoughts_diarymean + ple_suspicion_diarymean + ple_treatment_diarymean + ple_perception_diarymean + ple_thougtscontrol_diarymean + ple_familiarstrange_diarymean
  negaff_latent_b =~ angry_diarymean + sad_diarymean + irritated_diarymean + worried_diarymean

    # stressor_total_b <~ 1*stressor_9+stressor_10+stressor_11+stressor_12+stressor_13+stressor_15+stressor_16+stressor_17
  # ple_latent_b ~ stressor_total_b
  # negaff_latent_b ~ stressor_total_b

"

```

```{r}
fit_formative <- lavaan::sem(sem_stressor_formative, data = dat_diary, cluster = "id_esm", estimator = "ML")
```

```{r}
lavPredict(fit_formative) %>% colnames()
```


```{r}
modificationindices(fit_formative) %>% arrange(-mi)
```


```{r}
fitmeasures(
  fit_formative,
  fit.measures = 
    c(
      "chisq", "df", "pvalue","CFI","TLI", "RMSEA", "srmr_within", "srmr_between"
    )
)
```

```{r}
summary(fit_formative)
```

### stressor to observed negaff only

```{r}

dat_depi_stressor <-
  dat_diary %>% 
  select(id_esm, date_diary, stressor_9, stressor_10, stressor_11,
         stressor_12, stressor_13, stressor_15, stressor_16, stressor_17, contains("SCL_90_depr_diary_")) %>%
  filter_at(vars(stressor_9:SCL_90_depr_diary_13), all_vars(!is.na(.))) 

stressor_formative_negaff <- 
  "
level: 1
  
  stressor_total_w <~ 1*stressor_9+stressor_10+stressor_11+stressor_12+stressor_13+stressor_15+stressor_16+stressor_17
  
  # depr_latent_w =~ SCL_90_depr_diary_1+SCL_90_depr_diary_2+SCL_90_depr_diary_3+SCL_90_depr_diary_4+SCL_90_depr_diary_5+SCL_90_depr_diary_6+SCL_90_depr_diary_7+SCL_90_depr_diary_8+SCL_90_depr_diary_9+SCL_90_depr_diary_10+SCL_90_depr_diary_11+SCL_90_depr_diary_12+SCL_90_depr_diary_13
  
  SCL_90_depr_diary_1 ~ stressor_total_w
    SCL_90_depr_diary_2 ~ stressor_total_w

  
level: 2

  stressor_total_b <~ 1*stressor_9+stressor_10+stressor_11+stressor_12+stressor_13+stressor_15+stressor_16+stressor_17

   # depr_latent_b =~ SCL_90_depr_diary_1+SCL_90_depr_diary_2+SCL_90_depr_diary_3+SCL_90_depr_diary_4+SCL_90_depr_diary_5+SCL_90_depr_diary_6+SCL_90_depr_diary_7+SCL_90_depr_diary_8+SCL_90_depr_diary_9+SCL_90_depr_diary_10+SCL_90_depr_diary_11+SCL_90_depr_diary_12+SCL_90_depr_diary_13
   
  SCL_90_depr_diary_1 ~ stressor_total_b
      SCL_90_depr_diary_2 ~ stressor_total_b


  "

```

```{r}
fit_formative_negaff <- lavaan::sem(stressor_formative_negaff, data = dat_depi_stressor, 
                                    cluster = "id_esm",
                                    estimator = "MLR")
```

```{r}
summary(fit_formative_negaff)
```

```{r}
fitmeasures(
  fit_formative_negaff, 
  fit.measures = 
    c(
      "chisq", "df", "pvalue","CFI","TLI", "RMSEA", "srmr_within", "srmr_between"
    )
)
```
```{r}
modificationindices(fit_formative_negaff) %>% arrange(-mi)
```

### pca and factor analysis with the stressor variables that shows some variance

```{r}
prin <-
  dat %>%
  select(stressor_9, stressor_10, stressor_11, stressor_12, stressor_13, stressor_15, stressor_16, stressor_17) %>% 
    filter_at(vars(stressor_9:stressor_17), all_vars(!is.na(.)))


(parallel <- psych::fa.parallel(prin, fm = "pa"))

(principal <-
    psych::principal(prin, nfactors = 3, rotate = "oblimin"))
```
```{r}

dat_cfa_stressor <-
  dat_diary %>% 
  select(id_esm, three_day_block, stressor_9, stressor_10, stressor_11,
         stressor_12, stressor_13, stressor_15, stressor_16, stressor_17) %>%
  filter_at(vars(stressor_9:stressor_17), all_vars(!is.na(.))) 
  

cfa_stressor_syntax <- '

level: 1
      stressor_I  =~ stressor_9 +  stressor_10 +  stressor_11
      
      stressor_II  =~ stressor_12 +  stressor_13 # +  stressor_17
      
      stressor_III  =~ stressor_15 +  stressor_16
      
      # stressor_I ~~ stressor_II
      # stressor_II ~~ stressor_III
      # stressor_I ~~ stressor_III
      
level: 2
      stressor_I_b  =~ stressor_9 +  stressor_10 +  stressor_11
      
      stressor_II_b  =~ stressor_12 +  stressor_13 #+  stressor_17
      
      stressor_III_b  =~ stressor_15 +  stressor_16
      
      # stressor_I_b ~~ stressor_II_b
      # stressor_II_b ~~ stressor_III_b
      # stressor_I_b ~~ stressor_III_b
'

fit_stressor <- cfa(model = cfa_stressor_syntax, data = dat_cfa_stressor, std.lv = TRUE, cluster = "id_esm", estimator = "MLR")
```

```{r, warning = T}

fitMeasures(fit_stressor, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr_within", "srmr_between"))
```

```{r}
modificationindices(fit_stressor) %>% arrange(-mi)

```


```{r}
summary(fit_stressor)
```


```{r}
# within/betwwe-person factor loadings
(inspect(fit_stressor, what = "std")$within$lambda)
(inspect(fit_stressor, what = "std")$id_esm$lambda)
```


```{r}
# reliability of NA model
(reliability(fit_stressor))

```

```{r}

dat_stressor_lev_2 <-
  dat_cfa_stressor %>%
  select(id_esm) %>%
  distinct() %>%
  cbind(lavPredict(fit_stressor, newdata = dat_cfa_stressor[3:10], level = 2L))

dat_stressor_lev_1 <-
  dat_cfa_stressor %>%
  cbind(lavPredict(fit_stressor, newdata = dat_cfa_stressor[3:10], level = 1L)) %>%
  select(-c(stressor_9:stressor_17))

dat_stressor_both_levels <-
  dat_stressor_lev_1 %>%
  left_join(dat_stressor_lev_2, by = "id_esm") %>%
  mutate(stress_balance_cfa =  stressor_I + stressor_I_b,
         stress_social_cfa =  stressor_II + stressor_II_b,
         stress_control_cfa =  stressor_III + stressor_III_b)

dat_diary <-
  dat_diary %>% 
  left_join(dat_stressor_both_levels, by = c("id_esm", "three_day_block"))


```

