---
title: "x_mean_ple_models"
author: "Levente Ronai"
output: html_document
  html_document:
   theme: spacelab
   code_download: true
   toc: true
   toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r, include=F}

options(scipen = 999)

suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(xts))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(qgraph))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(lmerTest))
suppressPackageStartupMessages(library(sjPlot))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(car))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(performance))
suppressPackageStartupMessages(library(lmeresampler))

```

import data

```{r}
model_dat <- read.csv("data_processed/model_dat.csv")
```

```{r}
# calcluate mean PLEs for each beep from ple items

model_dat <- 
  model_dat %>%
  mutate(ple_mean = rowMeans(select(., c(ple_control:ple_familiarstrange)), na.rm = T))
```

```{r}

ple_list <- 
  model_dat %>% 
  select(ple_control:ple_familiarstrange) %>% 
  colnames()

```

```{r}
freq <- list()

for(ples in ple_list){
  freq[[ples]] <- 
    model_dat %>% 
    filter(!is.na(.data[[ples]])) %>% 
    reframe(freqs = table(.data[[ples]]))
  
}

print(freq)
```

```{r}
freq <- list()

for(ples in ple_list){
  freq[[ples]] <- 
    model_dat %>% 
    filter(!is.na(.data[[ples]])) %>% 
    reframe(mean = round(mean(.data[[ples]], na.rm = T), 2),
            median = median(.data[[ples]], na.rm = T),
            sd = round(sd(.data[[ples]], na.rm = T), 2)) 
  
}

print(freq)
```

testing predictive validity of stressor scale

```{r}

m_baseline_ple <-
  lmer(
    ple_mean ~ age + gender + day + beep +
      stressor_mean_centered_int + (stressor_mean_centered_int | id_esm), data = model_dat)

tab_model(m_baseline_ple,
          show.aicc = T, show.std = T)

```

### ~ ple

```{r}

m1 <-
  lmer(
    ple_mean ~
      day + beep + gender + age +
      stressor_mean_centered_int * mss_neg_score  +
      #     stressor_mean_centered_int * mss_pos_score  +
      #     stressor_mean_centered_int * mss_dis_score  +
      (stressor_mean_centered_int | id_esm), data = model_dat)

m2 <-
  lmer(
    ple_mean ~
      day + beep + gender + age +
      stressor_mean_centered_int * mss_neg_score  +
      stressor_mean_centered_int * mss_pos_score  +
      #     stressor_mean_centered_int * mss_dis_score  +
      (stressor_mean_centered_int | id_esm), data = model_dat)

m3 <-
  lmer(
    ple_mean ~
      day + beep + gender + age +
      stressor_mean_centered_int * mss_neg_score  +
      stressor_mean_centered_int * mss_pos_score  +
      stressor_mean_centered_int * mss_dis_score  +
      (stressor_mean_centered_int | id_esm), data = model_dat)


m4 <-
  lmer(
    ple_mean ~
      day + beep + gender + age +
      # stressor_mean_centered_int * mss_neg_score  +
      # stressor_mean_centered_int * mss_pos_score  +
      stressor_mean_centered_int * mss_dis_score  +
      (stressor_mean_centered_int | id_esm), data = model_dat)

m5 <-
  lmer(
    ple_mean ~
      day + beep + gender + age +
      # stressor_mean_centered_int * mss_neg_score  +
      stressor_mean_centered_int * mss_pos_score  +
      # stressor_mean_centered_int * mss_dis_score  +
      (stressor_mean_centered_int | id_esm), data = model_dat)

# saveRDS(m1, "models/m1.rds")
# saveRDS(m2, "models/m2.rds")
# saveRDS(m3, "models/m3.rds")
# saveRDS(m4, "models/m4.rds")
# saveRDS(m5, "models/m5.rds")

# m1 <- readRDS("models/m1.rds")
# m2 <- readRDS("models/m2.rds")
# m3 <- readRDS("models/m3.rds")

tab_model(m1,
          m2, 
          m3,
          m4,
          m5)
          #show.aicc = T, show.std = T)

```